name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.7]

    env:
      VERSION=`grep "version" < addon.xml | tail -n+2 | head -n1 | sed 's/ *version="//' | sed 's/"//' | tr -d '[[:space:]]'`

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --skip-lock
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics --exclude resources/lib/websocket
    - name: Test with pytest
      run: |
        pipenv run python -m pytest test
    - name: Make zip for Kodi
      run: |
        echo "Making zip of $VERSION"
        mkdir plugin.video.espn_3-$VERSION
        cp -R addon.py addon.xml LICENSE.txt resources/ plugin.video.espn_3-$VERSION
    - uses: actions/upload-artifact@master
      with:
        name: plugin.video.espn_3
        path: plugin.video.espn_3-$VERSION
